# DVC Pipeline Configuration
# Data version control for annotations, models, and generated outputs
# See: https://dvc.org/doc/user-guide/project-structure/dvcyaml-files

stages:
  train:
    cmd: >
      uv run edm train
      data/annotations
      --audio-dir ~/music
      --output outputs/training
      --epochs 50
      --batch-size 4
      --duration 30.0
    deps:
      - data/annotations
      - src/edm/training
      - src/edm/models
    params:
      - training.epochs
      - training.batch_size
      - training.learning_rate
    outs:
      - outputs/training/checkpoints:
          cache: true
      - outputs/training/logs:
          cache: false
    metrics:
      - outputs/training/metrics.json:
          cache: false
